services:
    custom-rpi-image:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi_prod_rails_app_docker:latest
        volumes:
            - ./custom-rpi-image:/home/imagegen/custom-rpi-image